Slovak language
bytefury/crater pull request #428
Opened 2021-03-23 13:03 UTC by BIIINO

Hello, 

there is almost 100% translated Slovak language - except few words from installation wizard which are beter understand in english.

Also creating pull request for mobile app right now.

Thank you in advance

2021-03-23 19:32 UTC, BIIINO commented
Mobile app version:

https://github.com/bytefury/crater-mobile/pull/14

2021-03-24 08:31 UTC, mohitpanjwani requested changes
Hey, Thank you for contributing. 

Please remove the changes from Report pages or add them as translatable keys so we can review this further :)

2021-03-24 08:31 UTC, mohitpanjwani commented on resources/assets/js/views/reports/ExpensesReport.vue
> +        'Dnes',
@BIIINO Hey, changing this list directly will update it for all languages (it'll show date range fields in Slovak even if you select english language)

In order to make this date range fields translatable, we need to add all of these strings as keys on `en.json` etc.

2021-03-24 08:31 UTC, mohitpanjwani commented on resources/assets/js/views/reports/ProfitLossReport.vue
> +        'Minulý štvrťrok',
Same issue here.

2021-03-24 08:31 UTC, mohitpanjwani commented on resources/assets/js/views/reports/SalesReports.vue
> +        'Tento mesiac',
Same issue here.

2021-03-24 08:31 UTC, mohitpanjwani commented on resources/assets/js/views/reports/TaxReport.vue
> +        'Minulý mesiac',
Same issue here.

2021-03-24 08:39 UTC, mohitpanjwani commented
Also I've just merged a PR for Vietnamese, so can you also fix those minor conflicts 👍

2021-03-24 08:57 UTC, BIIINO commented
Hi,

how can i add all these strings as translatable keys? For example:
-----------------------------------
"this_year": "Tento rok",     
-----------------------------------
Is that okay format ?

Thank you

2021-03-24 09:02 UTC, mohitpanjwani commented
> Hi,
> 
> how can i add all these strings as translatable keys? For example:
> 
> "this_year": "Tento rok",
> 
> Is that okay format ?
> 
> Thank you

Hey, yes that would be great. 

For now you can just add the key values for english and Slovak. 

Other languages which don't have this key defined, should automatically fallback to english.

2021-03-24 09:53 UTC, BIIINO commented
Tested on local installation but not recognized, removing these files.

2021-03-24 11:29 UTC, merged

2021-04-18 08:42 UTC, BIIINO commented
i am still trying to add for example these as transable key into en.json.

When i create line in en.json:
"this_year": "This year",
and
"this_year": "Tento rok",


nothing changed on web, still english. What else is necesery to be done for correct implementation ?

2021-04-18 08:48 UTC, BIIINO commented
@mohitpanjwani hint me please :)